### ISSUE TITLE
[BUG] Apparatus multiplayer is wrong!!!

### ISSUE THREAD

**Issue by Dantoresco** [Fredolx/lc-meteo-multiplier#5]
Because the way it's coded, the multipliers due to bad weather make the Apparatus worth LESS than the original value.
For example, Eclipsed with the 0.6 multiplayer makes the Apparatus cost 48 (0.6x80)

**Comment by Fredolx** [comment]
You're right, when I changed the values to the official values I forgot about this. Thank you. To explain further, I thought the values started at 1.0 because it was what was written in the decompiled code, but through digging I found that the official value for loot multi is 0.4 and it's loaded through a unity scene.

**Comment by Fredolx** [comment]
Fixed by https://github.com/Fredolx/lc-meteo-multiplier/commit/1a2bf21fc72bf5f93a2f4e85c31484d09d51f286
